== Thumbnail Handling

[discrete]
=== Overview

Xataface 3.0 includes automatic thumbnail generation for Container fields.  See the <<generating-thumbnails>> recipe for an example of how to use this feature.  You can also refer to the <<fieldsini-directives>> section to see the syntax of the  `transform` and `thumbnail.ACTIONAME` directives.

This section describes the PHP and HTTP APIs for Xataface's thumbnail feature.

=== How it works

If you add the `transform` directive to your container field, Xataface will automatically generate thumbnails for images that are uploaded to that field, at the time that they are uploaded.

e.g.

[source,ini]
----
transform="itunes300 fill:300x300; itunes1400 fill:1400x1400"
----

The first thumbnail (in this case itunes300) will be displayed by default whenever displaying this field's image.  You can configure a specific thumbnail to be used for a given action using the `thumbnail.ACTIONNAME` directive.  E.g. If you wanted to use the "itunes1400" thumbnail for the "list" action you would add:

[source,ini]
----
thumbnail.list=itunes1400
----


When using `Dataface_Record::display($fieldname)` and `Dataface_Record::htmlValue($fieldname)` it will respect these directives.  E.g. If you call `$record->display('myimage')` it will return the URL for the "itunes300" thumbnail when called inside a request for most actions, but it will return the URL for the "itunes1400" thumbnail when called inside a request for the "list" action.

If you look at the resulting URL generated by the `display()` method, you'll see something like:

`index.php?-action=getBlob&...&-thumb=itunes300`

It is the "-thumb" query parameter at the end that specifies the thumbnail.  If you remove that parameter, it will just return the full-sized image.

=== PHP API

The `Dataface_Record` and `Datafae_Table` classes include a few methods for dealing with thumbnails.  Some of these methods include:

`Dataface_Record::thumbnail($fieldname, $thumbnailType) : String `::
Returns the URL for a thumbnail of the given type of thumbnail.
+
====
Example:

.Getting thumbnail of type itunes1400 for the "logo" field in the record.
[source,php]
----
$imageUrl = $record->thumbnail('logo', 'itunes1400');
echo $imageUrl;
----

Output:

.Output shows that the "-thumb" GET parameter is set to "itunes1400", which is caused by the 2nd parameter of the above `thumbnail()` call.
[source,listing]
----
http://example.com/index.php?-action=getBlob&...&-thumb=itunes1400
----
====

`Dataface_Record::getThumbnailForAction($fieldname, $actionName) : String`::
Returns the URL for the thumbnail that should be used for the specified action name.  This is configured via the `thumbnail.$actionName` directive in the fields.ini file.
+
====
**Example:**

.fields.ini file definition for the logo field.
[source,ini]
----
[logo]
Type=container
transform="itunes300 fill:300x300; itunes1400 fill:1400x1400"
thumbnail.list=itunes1400
----

.PHP code getting URL for the "logo" field in three different ways.
[source,php]
----
echo $record->display('logo') ."\n";
echo $record->getThumbnailForAction('logo', 'list')."\n";
echo $record->getThumbnailForAction('logo', 'view');

----

.Output when request was for the "list" action.
[source,listing]
----
http://example.com/index.php?-action=getBlob&...&-thumb=itunes1400 <1>
http://example.com/index.php?-action=getBlob&...&-thumb=itunes1400 <2>
http://example.com/index.php?-action=getBlob&...&-thumb=itunes300 <3>
----
<1> `display()` returns URL with `-thumb=itunes1400` because of the "thumbnail.list=itunes1400" in the fields.ini file, and because the current request is for the "list" action.
<2> `getThumbnailForAction('logo', 'list')` returns "itunes1400" because of the "thumbnail.list" directive in the fields.ini file.
<3> `getThumbnailForAction('logo', 'view')` returns "itunes300" because there is no explicit "thumbnail.view" directive in the fields.ini file so it defaults to the first thumbnail type defined in the "transform" directive.

.Output when request is for the "view" action.
[source,listing]
----
http://example.com/index.php?-action=getBlob&...&-thumb=itunes300 <1>
http://example.com/index.php?-action=getBlob&...&-thumb=itunes1400
http://example.com/index.php?-action=getBlob&...&-thumb=itunes300
----
<1> Notice that the output of `display()` is different when it is executed as part of the "view" action.  In this case it adds the "-thumb=300" GET parameter because that is the effective thumbnail type for this action - no `thumbnail.view` directive is defined, so it falls back to the first thumbnail type defined in the `transform` directive.
====

`Dataface_Record::getThumbnailTypeForAction($fieldname, $actionName) : String`::
Returns the thumbnail type for the given action.  If there is an explicit directive for `thumbnail.$actionName` in the fields.ini file, then its value will be used.  Otherwise it will return the first thumbnail type defined in the `transform` directive.
+
====
**Example:**

.fields.ini file definition for the logo field.
[source,ini]
----
[logo]
Type=container
transform="itunes300 fill:300x300; itunes1400 fill:1400x1400"
thumbnail.list=itunes1400
----

.Sample PHP code
[source,php]
----
echo $record->getThumbnailTypeForAction('logo', 'list')."\n";
echo $record->getThumbnailForTypeAction('logo', 'view');
----

.Sample Output
[source,listing]
----
itunes1400 <1>
itunes300 <2>
----
<1> When `$actionName` is 'list' it outputs "itunes1400" because of the `thumbnail.list=itunes1400` directive in the fields.ini file.
<2> When `$actionName` is 'view' it outputs "itunes300" because there is no `thumbnail.view` directive defined in the fields.ini file so it falls back to the first thumbnail type defined in the `transform` directive.

====

`Dataface_Record::hasThumbnail($fieldname, $thumbName) : boolean`::
Checks if a record has a thumbnail of the given type for the specified field.  If the `transform` directive defines a thumbnail of the given `$thumbName` but the current record doesn't actually have a thumbnail stored of that type, then this will return `false`.  It only returns true if the record actually has a thumbnail of this type that can be displayed.  E.g. if the field is empty (has no image), then this also returns `false`.
+
====
**Example:**

[source,php]
----
if ($record->hasThumbnail('logo', 'itunes1400')) {
    // The record has a thumbnail of itunes1400 type.
    $thumbUrl = $record->thumbnail('logo', 'itunes1400');
    // ..
}
----
====

`Dataface_Record::getThumbnailTypes($fieldname) : string[]` ::
Returns a list of the thumbnails that are currently available for this record.  This only includes thumbnail types that actually exist.  It isn't sufficient for them to be listed in the `transform` directive.
+
====
**Example:**

.PHP Source
[source,php]
----
$types = $record->getThumbnailTypes('logo');
print_r($types);
----

.Output
[source,listing]
----
array(
    0 => itunes300,
    1 => itunes1400
)
----

====








