[#confini-directives]
== Conf.ini Directives

[discrete]
=== Overview

The conf.ini file is where most of the application-level configuration information is stored for a Xataface application. It contains information such as:

. database connection information
. which tables should appear in the tables menu.
. preference settings
. authentication settings
. which add-on modules are to be used
. output caching settings
. history/undo settings
. other misc settings.

TIP: This section documents some of the built-in configuration directives that Xataface supports, however, this file is extensible so you can add your own configuration directives as well (which you access in your PHP and Action definitions).

[discrete]
=== Sections

Every conf.ini file must contain at least the following sections:

_database::
Contains database connection info.
+
.Example `_database` section
[source,ini]
----
[_database]
  name=spokenpage
  user=root
  password=password
  host=localhost
  driver=mysqli
----
+
TIP: It is recommended to place the `[_database]` section in a separate file named `conf.db.ini.php` and include it in the `\__includes___` directive to make your app more portable.

_tables::
Contains a list of tables that are to be included in the navigation menu of the application.
+
.Example `_tables` section
[source,ini]
----
[_tables]
    people=People
    publications=Publications
----

The following optional sections may also be included:

_allowed_tables::
Specifies tables that should be explicitly allowed to override disallowed tables listed or matched in the _disallowed_tables section.	Since 0.7

_auth::
Contains information about authentication.	Since 0.6

_disallowed_tables::
A list of tables or patterns that match tables that should be blocked from being accessed directly through the application. By default any table beginning with an underscore, 'dataface_', or ending in '__history' are blocked. This prevents unintended access to some of the automatically created tables in Xataface.	Since 0.7

_feed::
Configuration options for RSS feeds that are generated by the application.	Since 1.0

_history::
Settings pertaining to the history feature (e.g. whether it has been enabled).	Since 0.7

_index::
Settings for the full site search indexing.	Since 1.0

_modules::
A list of modules that are enabled for this application.	Since 1.0

_output_cache::
Output cache settings. Using output caching can dramatically improve performance for busier sites.	Since 0.8

_themes::
A list of the themes that are to be applied to the application. Since 0.8

table_labels::
A list that defines friendly labels for displaying table names. Similar to the `[_tables]` section, but these tables do not appear in the application's navigation menu by default. This is also the only method to display friendly table names in the search index results as of Xataface 2.1 or prior. (See Editing Search Results >> How Do I change table names). Also see the <<fieldsini-table-label,label global directive in the fields.ini_file>>.	Since always.

=== Stand-alone Attributes

Stand-alone attributes for an INI file must appear at the beginning of the INI file (before any of the sections). The conf.ini may contain the following stand-alone attributes.

cache_queries::
Enables query caching. Enabling this feature can yield drastic performance improvements especially on busy sites with large databases.
+
**Accepted Values**: boolean (0 or 1)
+
**Since** 1.2

cache_queries_log::
Enables logging of query caching to the file /tmp/querylog.log so that you can tell whether your queries are being cached, and which ones are being cached.
+
**Accepted Values** boolean (0 or 1)
+
**Since ** 1.2

default_action::
The default action to be performed if it is not explicitly specified in the query (e.g. 'list', 'find', 'edit').
+
**Accepted Values** string.  Name of action.
+
**Default Value** 'list'.
+
**Since** 0.6

debug::
If this is set to 1, then the application will run in debug mode which displays the available slots and blocks on the screen, along with some other debug information.
+
**Accepted Values** 0 or 1
+
**Default Value** 0
+
**Since** 0.6

default_browse_action::	The default action to perform in the details tab. E.g. When you click on the "details" tab there are a number of sub-tabs including 'view', 'edit', etc... . The default value for this directive is 'view'. If you want to go directly to the edit form when clicking on a record in list view, you would set default_browse_action to 'edit'.	string
+
**Since** 0.6

default_language::	The default language to use. This is the 2-digit ISO language code. If this value is not specified it defaults to the first language listed in the [languages] section.	string (2-digit ISO language code)
+
**Since** 0.6

default_limit::
The default limit (i.e. the number of records to show per page) if none is explicitly specified in the query.
+
**Accepted Values** positive integer.  E.g. 100
+
**Default Value** 30
+
**Since** 0.6

default_table::
The default table to show if none is specified by the query.
+
**Default Value:** The first table listed in the `[_tables]` section.
+
**Since**	0.6

disable_session_ip_check::
Default behaviour automatically tracks the IP address of the user when they log in. If a request is made for a session from a different IP then the session is automatically destroyed and the user is logged out.
+
**Accepted Values** boolean	(0 or 1)
+
**Since** 1.3rc4

title::
A title for the application (appears in the browser title bar).
+
**Since** 0.6

[#confini-include-directive]
\\__include__::
A comma-delimited list of configuration files that you wish to include.
+
====
This list can be used to separate your configuration into multiple files, or to provide different configurations for different host environments.  It is common, for example, to factor your database connection information into a separate file named "conf.db.ini.php" which is not kept in version control to make the application more portable.

**Example:** Placing database configuration in separate file

.conf.ini.php file
[source,ini]
----
;<?php exit;

__include__=conf.db.ini.php

[_tables]
   table1=My First Table
   table2=My Second Table
----

.conf.db.ini.php file
----
;<?php exit;

[_database]
   host=localhost
   name=mydb
   user=mydbuser
   password=dbpass
----

NOTE: For security it is recommended to add the ".php" extension to all of your INI files to prevent the web server from publishing them.  The first line, then is always `;<?php exit;` as this will be ignored when parsing the file as an INI file, and it will cause execution to exit when parsing as a PHP file.

**Placeholder Variables**

Since version 3.0, you can use placeholder variables in your \\__include__ directive which allow you to specify a different path based on the environment.  The following placeholders are supported:

`{host}`::
Will be replaced by the HTTP host name of the request.  E.g. if the app is being accessed at `http://example.com`, then `{host}` placeholders will be replaced with "example.com".
`{port}`::
Will be replaced by the HTTP port for the request.

.Example conf.ini.php using placeholders
[source,ini]
----
;<?php exit;

__include__=conf.db.ini.php, hosts/{host}/{host}.conf.ini.php
----

In the above example, if the app is accessed at example.com, then it would include the conf file located at `hosts/example.com/example.com.conf.ini.php`, but if it is accessed at `localhost`, then it would load the config file at `hosts/localhost/localhost.conf.ini.php`.


**Optional Includes**

**TLDR:**  Add `?` to the end of a file path to make it an optional include. E.g. `\\__include__=hosts/{host}/{host}.conf.ini.php?`

By default, if an include fails (because the included file doesn't exist), then an exception will be thrown when the app is loaded.  In some cases you may want the include to be "optional" so that it just fails to load silently if the file can't be found.  You can add `?` to the end of a file path to make it optional.

====


