[#searching]
== Searching

The following section include tips on configuring search support in Xataface application.

=== Case-Sensitive Searches

[discrete]
==== Problem

You searches on a particular column to be case-sensitive.  (E.g. If the user searches for "Bob", it should match "Bob" but not "bob").

[discrete]
==== Solution

Use the `collate` fields.ini directive to "utf8_general_cs" (or any other supported collation that is case-sensitive.

E.g.

.fields.ini file, specifying that searches of the "name" field should be case sensitive.
[source,ini
----
[name]
   collate=utf8_general_cs
----

[discrete]
==== Discussion

By default, the case-sensitivity of searches depends on the collation of the underlying table and column in MySQL.  If the column was defined with a case-sensitive collation (e.g. `utf8_general_cs`), then all searches on this column will be case-sensitive.  If, however, it was defined with a case-insensitive collaction (e.g. `utf8_general_ci`), all searches will be case-insensitive.  If you want to change the behaviour of the app, you could simply change the underlying collation.  But in some cases you may not want to modify the table structure (or you won't have access to the table structure).  In such cases, the "collate" directive is helpful.

=== Explicitly Specifying Case-sensitivity of a Search

[discrete]
==== Problem

You want to perform a case-sensitive search on a field that has a case-insensitive collation.

[discrete]
==== Solution

Wrap the query value in a command wrapper, and use the "cs" command to specify "case-sensitive" (or "ci" to specify case-insensitive").

E.g.

If you want to search for "Bob" in the name field, enter the following in the search field for "Bob".

----
#Bob#cs
----

If you, instead wanted to explicitly perform a case-insensitive search you would enter

----
#Bob#ci
----

=== Making Columns Not-Searchable

[discrete]
==== Problem

The main search box at the top of the application searches for matches in all of the char, varchar, and text fields by default.  What if you want to only match against specific fields?

[solution]
==== Solution

Use the `not_searchable` fields.ini directive on any field cause searches *not* to match using that column.

E.g. If I don't want the search field to match on a the "private_info" column, I could do the following:

.fields.ini directives, disabling search matching on the private_info field
[source,ini]
----
[private_info]
    not_searchable=1
----

Now, if the user enters a search in the top search box, it won't match against the "private_info" column.

You can "inverse" this behaviour, and make all of the columns not searchable by default, using the `\\__global__` section.

E.g.

.Making all fields unsearchable except for the `myfield` column.
[source,ini]
----
[__global__]
    not_searchable=1
    
[myfield]
    not_searchable=0
----

[IMPORTANT]
====
`not_searchable` only affects the top search box (i.e. the `-search` query parameter).  Users can still peform "finds" on a field with `not_searchable=1`by directly performing a find on that column using either the "advanced find" form, column search, filters, or via URL conventions (e.g. `myfield=someval`).

If you want to make a field completely "un-findable", you should use the `not_findable` directive.  
====


