[#action-sheet]
=== xataface.ActionSheet



A component for displaying menu in a Sheet.  ActionSheets can be displayed from the bottom, left, top, or right positions, and they transition in over top of the existing page content.

**Since 3.0**

[discrete]
==== Bootstrapping

.Loading Script in PHP
[source,php]
----
xf_script('xataface/components/ActionSheet.js');
----

.Loading Script in Javascript using `require`
[source,javascript]
----
//require <xataface/components/ActionSheet.js>
----

[discrete]
==== Initialization Options

Use `new ActionSheet(options)` to create a new sheet.  The following options are allowed:

modelEl::
`HTMLElement` of a `<ul>` tag that defines the menu options to appear in this sheet.  See <<modelEl-structure>>.
position:: The position where the sheet should be displayed. `top`, `left`, `right`, `bottom`.
parent::
Optional `ActionSheet` that is the parent of this `ActionSheet`.  If this property is provided then the sheet will have a "back" button to navigate back to the parent instead of a "close" button.

[discrete]
===== Alternative Intialization Options

The `ActionSheet` constructor can also be called simply with single `String` or `HTMLElement` argument.  In the `String` case, the string will be interpreted as the query selector to the `<ul>` tag to use for the `modelEl` property.  In the `HTMLElement` case, it will be used as the `modelEl` property itself.

[#modelEl-structure]
.Structure of the `modelEl` `<ul>` tag.
[sidebar]
****
The `modelEl` property should be an `HTMLElement` `<ul>` tag.  The menu options are constructed based on the `<li>` items inside the `<ul>` tag.

. Each `<li>` tag may include an `<a>` tag, which defines where the menu links to.
. The nested `<a>` tag may contain a `<span>` tag which will be used as the menu item label.
. The nested `<a>` tag may also include an `<i>` with class "material-icons" which specifies a material icon to use in the menu item.
. The `<li>` tag may also include a `<ul>` tag which will be treated as a sub-menu.  This `<ul>` tag should not be nested inside the `<a>` tag.

**Example**

[source,html]
----
<ul>
    <li>
        <a href="index.html">
            <i class="material-icons">home</i>
            <span>Home</span>
        </a>
    </li>
    <li>
        <a href="about.html">
            <i class="material-icons">info</i>
            <span>About</span>
        </a>
    </li>
    <li>
        <a href="javascript:void(0)" onclick="sayHello()">
            <i class="material-icons">help</i>
            <span>Say Hello</span>
        </a>
    </li>
    <li>
        <span>More Options</span>
        <ul>
            <li>
                <a href="subpage1.html">Subpage 1</a>
            </li>
            <li>
                <a href="subpage2.html">Subpage 2</a>
            </li>
        </ul>
</ul>
    </li>
</ul>
----

The above example demonstrates a fairly simple menu that includes one sub-menu.  Notice that the "sayHello" option uses an `onclick` handler instead of an "href" attribute.  This is fine.  When the `ActionSheet` constructs its menu based on this model, it will call `click()` on the actual modelEl's `<a>` tag, so that clicking on the option in the `ActionSheet` is pretty much the same as having clicked on the `modelEl` element link itself.

****

[discrete]
==== Properties

parent::
Reference to the parent `ActionSheet` instance, if one was provided in the constructor.

[discrete]
==== Methods

show(initialHeight)::
Show the sheet.  Takes optional `int` parameter *initialHeight* specifying the starting height of the ActionSheet.  This is used internally when showing a submenu so that the transition to and from the child menu is smooth.

close(all)::
Close the sheeet.  Takes optional `boolean` argument *all* which, if true, will close all parent sheets as well.  Default behaviour is to navigate back to the parent if the sheet has a parent.

[discrete]
==== Usage Example

.Example implementation for the FAB button which opens the page actions menu.
[source,javascript]
----
//require <xataface/components/ActionSheet.js>
(function() {
    var ActionSheet = window.xataface.ActionSheet;

    /**
     * Function to install the FAB button.
     * This will be called after the page is finished loading.
     * See DOMContentLoaded event listener registration below.
     */
    function installFab() {
        // Convenience reference to jQuery
        var $ = jQuery;

        // Add a click handler to the zoom button.
        $('#zoomBtn').click(function() {

            // Get the page actions <ul> tag that
            // was rendered elsewhere on the page.  This is a standard
            // menu that is used in the Desktop theme that includes
            // all of the actions that are relevant to the current page.
            // The menu is hidden in the mobile theme, but we'll use
            // it as the model for the FAB button here so that its
            // actions can still be used in mobile.
            var pageActionsUl = $('div.page-actions > nav > ul').first();
            if (pageActionsUl.length > 0) {
                var menu = new ActionSheet(pageActionsUl.get(0));
                menu.show();
            }

        });

        // The "zoom" section has a `display:none` style directive
        // in the HTML template so that it isn't displayed before
        // we've had a chance to set it up.
        // Remove that style directive now that it should be all set up.
        $('.zoom').css('display', '');
    }

    // Some code omitted here for clarity

    window.addEventListener('DOMContentLoaded', installFab);
})();
----

That example references some HTML tags that are defined in the `Dataface_Main_Template.html` template.  Let's look at those here.

`div.page-actions > nav > ul`::
This is a reference to the page actions.  They are rendered in the HTML template as follows:
+
[source,html]
----
<div class='page-actions'>
    {block name="before_menus"}
    {define_slot name="menus"}
        {include file="Dataface_TableView_menus.html"}
    {/define_slot}
    {block name="after_menus"}
</div>
----
+
And the `Dataface_TableView_menus.html` renders a `<ul>` tag with the menus.

`#zoomBtn` and `.zoom`::
These are references to the zoom section and button defined in the template as follows:
+
[source,html]
----
{define_slot name="fab"}
    {*
        The FAB (floating action button), which uses the table_actions_menu
        category.

        Exclude actions from the FAB using the #large# tag in the action.
        Include actions in the FAB by adding materialIcon. If action doesn't
        have materialIcon, it won't be included in the FAB.

    *}

     {script src="xataface/fab.js"}
     <div class="zoom mobile" style="display:none">
         <a class="zoom-fab zoom-btn-large" id="zoomBtn">
            <i class="material-icons">menu</i>
         </a>

     </div>

{/define_slot}
----
